### ISSUE TITLE
v 2.0.0 failing to install via NuGet

### ISSUE THREAD

**Issue by mrtnkrstn** [slodge/Cirrious.FluentLayout#15]
With error

`Could not install package 'Cirrious.FluentLayout 2.0.0'. You are trying to install this package into a project that targets 'MonoTouch,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework.`

My project is not targeting the Unified API (yet) - could that be the reason for the error? If so, what earlier version can I install?

Thanks!

**Comment by slodge** [comment]
Thanks for your email.

For free open source support, I point people towards open public
communication - e.g. towards StackOverflow. A question and answer in public
can involve 100s of people - a question and answer in email involves just
two.

For paying customers, I do work in email. But most people seem to prefer
"free"!

Stuart

**Comment by gshackles** [comment]
Going through some old issues...as of 2.0 we are indeed built on the unified API. That was also our first NuGet release, so if you need a non-unified version your best bet is to pull down the code from before that commit and create a build that way.

I do suggest you just migrate to unified if you haven't already, though! :smile:
